version: "3"

services:
  etcdctl-client:
    image: quay.io/coreos/etcd:v3.6.1
    depends_on:
      - etcd0
      - etcd1
      - etcd2
    entrypoint: /bin/sh
    command: -c 'while true; do sleep 3600; done'
    environment:
      ETCDCTL_API: '3'
      ETCDCTL_ENDPOINTS: 'http://etcd0:2379,http://etcd1:2379,http://etcd2:2379'

  etcd0:
    image: quay.io/coreos/etcd:v3.6.1
    volumes:
      - etcd-data0:/etcd-data
    command: /usr/local/bin/etcd --name etcd0 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://etcd0:2380 --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 --initial-cluster-token etcd-cluster-1 --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"

  etcd1:
    image: quay.io/coreos/etcd:v3.6.1
    volumes:
      - etcd-data1:/etcd-data
    command: /usr/local/bin/etcd --name etcd1 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd1:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://etcd1:2380 --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 --initial-cluster-token etcd-cluster-1 --initial-cluster-state new
    ports:
      - "2379"
      - "2380"

  etcd2:
    image: quay.io/coreos/etcd:v3.6.1
    volumes:
      - etcd-data2:/etcd-data
    command: /usr/local/bin/etcd --name etcd2 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd2:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://etcd2:2380 --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 --initial-cluster-token etcd-cluster-1 --initial-cluster-state new
    ports:
      - "2379"
      - "2380"

volumes:
  etcd-data0:
  etcd-data1:
  etcd-data2:
